chore: fix another kpathsea build failure with emscripten
When you `emmake make` it will report the following error:

```
libtool: compile:  /home/osboxes/work/emsdk/upstream/emscripten/emcc -DHAVE_CONFIG_H -I. -I./.. -I./.. -DMAKE_KPSE_DLL -Wimplicit -Wreturn-type -g -O2 -MT libkpathsea_la-xgetcwd.lo -MD -MP -MF .deps/libk
pathsea_la-xgetcwd.Tpo -c xgetcwd.c  -fPIC -DPIC -o .libs/libkpathsea_la-xgetcwd.o
xgetcwd.c:118:13: error: use of undeclared identifier 'kpse'; did you mean 'else'?
            LIB_FATAL2("No inode %d/device %d in parent directory",
            ^
./../kpathsea/lib.h:98:3: note: expanded from macro 'LIB_FATAL2'
  LIB_START_FATAL (); fprintf (stderr, str, e1, e2); END_FATAL ()
  ^
./../kpathsea/lib.h:91:35: note: expanded from macro 'LIB_START_FATAL'
  fprintf (stderr, "%s: fatal: ", kpse->invocation_name);
                                  ^
xgetcwd.c:118:13: error: expected expression
./../kpathsea/lib.h:98:3: note: expanded from macro 'LIB_FATAL2'
  LIB_START_FATAL (); fprintf (stderr, str, e1, e2); END_FATAL ()
  ^
./../kpathsea/lib.h:91:35: note: expanded from macro 'LIB_START_FATAL'
  fprintf (stderr, "%s: fatal: ", kpse->invocation_name);
                                  ^
xgetcwd.c:119:20: warning: format specifies type 'int' but the argument has type 'ino_t' (aka 'unsigned long long') [-Wformat]
                   cwd_stat.st_ino, cwd_stat.st_dev);
                   ^~~~~~~~~~~~~~~
./../kpathsea/lib.h:98:45: note: expanded from macro 'LIB_FATAL2'
  LIB_START_FATAL (); fprintf (stderr, str, e1, e2); END_FATAL ()
                                       ~~~  ^~
1 warning and 2 errors generated.
emcc: error: '/home/osboxes/work/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten
-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/home/osboxes/work/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysro
ot/include/compat -DHAVE_CONFIG_H -I. -I./.. -I./.. -DMAKE_KPSE_DLL -Wimplicit -Wreturn-type -g3 -O2 -MT libkpathsea_la-xgetcwd.lo -MD -MP -MF .deps/libkpathsea_la-xgetcwd.Tpo -c -fPIC -DPIC xgetcwd.c -o
 .libs/libkpathsea_la-xgetcwd.o' failed (returned 1)
make[2]: *** [Makefile:1490: libkpathsea_la-xgetcwd.lo] Error 1
make[2]: Leaving directory '/home/osboxes/work/xetex.wasm/xetex/source/texk/kpathsea'
make[1]: *** [Makefile:1722: all-recursive] Error 1
make[1]: Leaving directory '/home/osboxes/work/xetex.wasm/xetex/source/texk/kpathsea'
make: *** [Makefile:877: all] Error 2
emmake: error: 'make' failed (returned 2)
```

The root cause why normal `make` will succeed and `emmake make` will
fail is the same as with previous commit
0056e1774f045b2977d97a0e31ff989bdf4fde1d, i.e, `make` and `emmake make`
will go to different path based on the value of `GETCWD_FORKS`.

Official kpathsea seems aware of this problem, thus they've added a
[comment](https://github.com/TeX-Live/texlive-source/blob/trunk/texk/kpathsea/lib.h#L90).

I don't have time to dig into this, thus here I just try a simple fix
and it seems working.