refactor: finally able to compile xetex to wasm
A sample session:

```
$ node build/texk/web2c/xetex
lstat(/home/osboxes) failed ...
/home/osboxes: No such file or directory
Aborted(Assertion failed: ret, at: progname.c,316,remove_dots)
/home/osboxes/work/xetex.wasm/xetex/build/texk/web2c/xetex:130
      throw ex;
      ^

RuntimeError: Aborted(Assertion failed: ret, at: progname.c,316,remove_dots)
    at abort (/home/osboxes/work/xetex.wasm/xetex/build/texk/web2c/xetex:870:11)
    at ___assert_fail (/home/osboxes/work/xetex.wasm/xetex/build/texk/web2c/xetex:1266:7)
    at kpathsea_selfdir (<anonymous>:wasm-function[4279]:0x2bbcaf)
    at kpathsea_set_program_name (<anonymous>:wasm-function[4280]:0x2bbcfc)
    at kpse_set_program_name (<anonymous>:wasm-function[4282]:0x2bbee5)
    at maininit (<anonymous>:wasm-function[65]:0x49ca)
    at main (<anonymous>:wasm-function[76]:0x97c4)
    at /home/osboxes/work/xetex.wasm/xetex/build/texk/web2c/xetex:908:22
    at callMain (/home/osboxes/work/xetex.wasm/xetex/build/texk/web2c/xetex:6740:15)
    at doRun (/home/osboxes/work/xetex.wasm/xetex/build/texk/web2c/xetex:6790:23)

$ ls -l build/texk/web2c/xetex build/texk/web2c/xetex.wasm
-rw-rw-r-- 1 osboxes osboxes   255524 Mar 22 11:24 build/texk/web2c/xetex
-rwxrwxr-x 1 osboxes osboxes 16857189 Mar 22 11:24 build/texk/web2c/xetex.wasm

$ head -n 7 build/texk/web2c/xetex
// include: shell.js
// The Module object: Our interface to the outside world. We import
// and export values on it. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(Module) { ..generated code.. }
// 3. pre-run appended it, var Module = {}; ..generated code..
// 4. External script tag defines var Module.
```

We can see that xetex has been compiled to wasm successfully. However,
it still need proper FS setup in order to run.

We need to enable `-Wno-implicit-function-declaration` flag otherwise
the build process will report errors like:

- `error: call to undeclared library function 'va_start'`
- `error: call to undeclared library function 'va_end'`

I am not sure about the root cause here though.